### ISSUE TITLE
[rdx compile] fails for default app w/o npm install

### ISSUE THREAD

**Issue by 100ideas** [resistdesign/rdx#18]
A user expects `rdx compile` to work after creating the default app with `rdx app -d y`.

`rdx compile` fails with a freshly-built default app because `npm install` hasn't been run.

consider automatically executing `npm install` as part of `rdx app -d y`, or adding info to the readme.

**Comment by resistdesign** [comment]
Yeah the plan was to log a message about running `npm i` and I forgot :P
