### ISSUE TITLE
how to serve images, fonts, other static files

### ISSUE THREAD

**Issue by 100ideas** [resistdesign/rdx#19]
What convention should be followed for including static assets, such as images & fonts? I poked around in the webpack config builder & saw the loader in common that seems set up for images, but I can't figure it out. None of my static assets besides the files in `index-icons/`are being compiled into my app.

Where should I store image files used in my app, and how should I reference them in my app? For instance, how do I access `app_logo.svg` from a react app component `src/components/LogoAppBar.js` that I'm importing in my main `App.js`: 

``` javascript
//...
  render() {
    return (
      <Toolbar style={styles.ToolBar}>
        <ToolbarGroup firstChild={false}>
          <img style={styles.svgLogo} src="./images/app_logo.svg" />
        </ToolbarGroup>
//...
```

**Comment by resistdesign** [comment]
You want to import the image like this:

`import MySrc from './folder/file.svg';`

The compiler will copy the file to the appropriate place in the output directory.

At runtime, `MySrc` will be a string URL. So you pass that to your `img` like this:

`<img src={MySrc} />`

And that *should* work!

**Comment by resistdesign** [comment]
I need to add a lot to the docs at some point, including this :)

**Comment by resistdesign** [comment]
Just a note, you **can** put `img` tags with a `src` in your `HTML` file and it will copy those files to the output for you as well. This is for when you need some default layout in your "page" that's always there.

**Comment by 100ideas** [comment]
@resistdesign Thanks for the explanation! Got it.

I don't understand webpack very well. In a different project, I was using the file loader to copy images I kept in `/public/images/` over to `/dist/images/`, and referencing them with relative urls in the `src` attribute in my .jsx files. I wasn't assigning hashes to the file names, so I didn't need to import the image files in js to get their full path - I already knew what it was.

I guess I was trying to figure out how to do something similar w/ rdx. But `import`ing them and getting the cacheble file name will be better.

Anway here's the relevant section of my webpack config from the other project if you are curious.

```javascript
/*
public/
├── actions/
├── api/
├── components/
├── constants/
├── fonts/
├── helpers/
├── images/
├── routes/
├── stores/
├── index.html
├── index.jsx
└── index.styl
*/

const PATHS = {
  PUBLIC: path.join(__dirname, 'public'),
  LIB: path.join(__dirname, 'lib'),
  DIST: path.join(__dirname, 'dist')
};

module.exports = {
  entry: {
    app: PATHS.PUBLIC,
  },
  output: {
    path: PATHS.DIST,
    filename: '[name]-[hash].min.js',
  },
  module: {
    loaders: [
      {
        test: /\.css$/,
        loader: extractCss.extract('style', ['css', 'postcss']),
      },
      {
        test: /\.(js|jsx)$/,
        loader: 'babel',
        include: [PATHS.PUBLIC, PATHS.LIB],
        query: {
          presets: ['react', 'es2015', 'stage-1'],
          plugins: ['transform-decorators-legacy'],
        },
      },
      {
        test: /\.(jpe?g|png|gif|ico)$/i,
        loader: "file?name=images/[name].[ext]",
      },
    ],
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: 'public/index.html',
      inject: 'body',
      filename: 'index.html',
    }),
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.optimize.UglifyJsPlugin({
      compressor: {
        warnings: false,
        screw_ie8: true,
      },
    }),
    new StatsPlugin('webpack.stats.json', {
      source: false,
      modules: false,
    }),
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('production'),
      },
    }),
    extractCss,
    extractStyl,
  ],
  postcss: () => [autoprefixer],
  resolve: {
    extensions: ['', '.js', '.jsx'],
  },
};
```

**Comment by resistdesign** [comment]
Just fyi, you don't need the hash, but it's for cache busting :)
