### ISSUE TITLE
Files not getting compiled as the correct types under Windows 10

### ISSUE THREAD

**Issue by bradisbell** [resistdesign/rdx#22]
CSS compilation fails when the file contains the following directive:

```
@charset "utf-8";
```

The error:

> SyntaxError: Unexpected character '@' (9:0)

Are there any options to this tool to ignore CSS and just copy it over?

**Comment by resistdesign** [comment]
@bradisbell With WebPack you can require/import with `!` like this `!./my-file` to avoid all loaders. That may work. Also, is your file a `.less` file?

**Comment by bradisbell** [comment]
@resistdesign I'll try that, thanks.  I tried .css, and .less.  Also I'm seeing now that even the example app has the same problem, with any content in the CSS file.  Whatever the first significant token is, it throws unexpected token.  It looks like it's trying to handle CSS as JS.

**Comment by resistdesign** [comment]
It's an issue with the less loader so I'm waiting on that.

**Comment by bradisbell** [comment]
I'm getting a similar thing on HTML... 

> Module parse failed C:\path\index.html Unexpected token (1:0)
> You may need an appropriate loader to handle this file type.
> SyntaxError: Unexpected token (1:0)

Yet, there is HTML output in `public/`...

Strange.

**Comment by resistdesign** [comment]
Odd, any chance you can make a repo with code demonstrating these issues so I can debug it?

**Comment by bradisbell** [comment]
Yeah, I'm on it!  In the mean time, is there some sort of environment issue you can think of?  Any other requirements outside of RDX for WebPack or whatever that need to be checked?  I tried downgrading to the WebPack mentioned in your package.json, but no dice there.

**Comment by bradisbell** [comment]
@resistdesign No need to make a test repo, your example repo (https://github.com/resistdesign/rdx-example) has the same issues on my system.

```
rdx compile -i src\index.html > rdx.txt
```
[rdx.txt](https://github.com/resistdesign/rdx/files/1149849/rdx.txt)

**Comment by resistdesign** [comment]
Are you on Windows?

**Comment by bradisbell** [comment]
Yes.

**Comment by bradisbell** [comment]
Disregard my previous log... I had forgotten to run `npm install` on that run.  Here's an updated log.  Now with WebPack v3.2.0.

[rdx.txt](https://github.com/resistdesign/rdx/files/1149878/rdx.txt)

**Comment by resistdesign** [comment]
rdx handles the install of webpack 1 for you. It wasn't made for 2 or 3. That needs to be done still.

AND I haven't done a lot of testing on Windows so all of these bugs make sense. I'll have to fire up a VM and see what needs to be fixed :P

**Comment by bradisbell** [comment]
This definitely seems to be a Windows-specific issue.  Tried it under Ubuntu 14.04 and all is well on this front.

**Comment by resistdesign** [comment]
Crap :P

**Comment by resistdesign** [comment]
I'm not seeing this problem now in 2.0.9+, please reopen if you have trouble.
