### ISSUE TITLE
Ability to set output path

### ISSUE THREAD

**Issue by bradisbell** [resistdesign/rdx#23]
When compiling, it would be helpful to be able to set an output path.

**Comment by resistdesign** [comment]
You can, run `rdx -h` to see the options. But I think it's `-o`.

**Comment by resistdesign** [comment]
https://github.com/resistdesign/rdx/blob/master/src/Commands/Compile.js#L23

**Comment by bradisbell** [comment]
Cool, thanks!  Would be great to see this in the README so that others can find it when they come across your project.  This is a solid project by the way, if I can get it working.  :-)

**Comment by resistdesign** [comment]
You're right, I need to do that. And you should get it working, I use it all the time. Just shoot another question if you need anything :)
