### ISSUE TITLE
Path references seem relative to current working directory, not entry point HTML file

### ISSUE THREAD

**Issue by bradisbell** [resistdesign/rdx#24]
Suppose I have the following in my HTML file, `src/index.html`:

```
<link rel="stylesheet" href="./css/index.css" />
```

If I run the following from the root of the project...:

```
rdx compile -a src/index.html
```

... the compilation will fail because the CSS file is at `src/css/index.css`, not `css/index.css`.  I think that the `.` reference should be the HTML file.  Note that it seems to get past this step if I don't specify `./`.  If this is intentional behavior, it probably makes sense to document as well!  Thanks!

**Comment by resistdesign** [comment]
Should be ok since 2.0.9.
