### ISSUE TITLE
Default `--open` doesn't work due to invalid address `0.0.0.0`

### ISSUE THREAD

**Issue by bradisbell** [resistdesign/rdx#25]
There's a minor issue where if using all the default options for `serve` with `--open`, the browser on some systems will fail to navigate to a working page.  This is due to the fact that `0.0.0.0` is suitable for listening on any interface but is not a valid address for actually connecting to.

The issue seems to be with this line:  https://github.com/resistdesign/rdx/blob/master/src/Commands/Serve.js#L42

I'd suggest that if `0.0.0.0` is detected as the bind address, that `127.0.0.1` be used when opening the browser.  Then, it should work anywhere.

**Comment by resistdesign** [comment]
Hmmm, I always put 0.0.0.0 in chrome and it seems to work, what browsers are you having issues with?
