### ISSUE TITLE
Original files overwritten with minified versions

### ISSUE THREAD

**Issue by bradisbell** [resistdesign/rdx#26]
It seems RDX is overwriting my files with the minified compiled versions, while at the same time putting copies in `public/`.

**Comment by resistdesign** [comment]
Wow, it really doesn't like Windows. I'm sorry, node, webpack and the libraries used should work the same on all systems for the most part, but this seems like wildly different behavior. And the file pathing in rdx was given a lot of careful consideration given that the whole point is to pull paths from HTML and do a crazy dance so you don't have to. Again, very sorry you're experiencing this, I will do my best to unearth and correct these issues. In the mean time I hope you've committed your work and didn't lose anything :(

**Comment by bradisbell** [comment]
Version control is magic.  :-)

**Comment by resistdesign** [comment]
@bradisbell I just released version `2.0.9` with fixes for windows pathing problems in 2 files.
I ran `rdx app` and made a test app and tried both `rdx serve` and `rdx compile`. Both seem to work as expected now. Please give it a whirl and close any issues you no longer see and feel free to open new ones if need be :)

**Comment by bradisbell** [comment]
Thank you sir!  I'll check it out.

**Comment by resistdesign** [comment]
@bradisbell I can't recreate this now, reopen if you still get this problem :)
