### ISSUE TITLE
Can't use import {module} from "module-name"

### ISSUE THREAD

**Issue by bradisbell** [resistdesign/rdx#28]
I'm trying to build a project that uses TaffyDB, with an import statement like this:

```
import {taffy} from 'taffydb';
```

This import statement doesn't work with whatever RDX is using to compile the JS.  I end up with an error in-browser:

> Uncaught TypeError: (0 , b.taffy) is not a function

The README for the project says RDX supports ES6, but it isn't clear if that means ES6 is transpiled to ES5 via Babel or similar, or if the ES6 is just pass-through for the sake of bundling.  It also isn't clear what sorts of import styles are supported.

Is this a bug, or just something needing documented?  Thank you.

(RDX v2.0.5 on Ubuntu)

**Comment by resistdesign** [comment]
@bradisbell Try importing it with a `!` at the beginning of the file name, like this: `!./myfile`. That will disable loaders. It's probably not able to be transpiled.

I will look at documenting this. There is a milestone related to this here: https://github.com/resistdesign/rdx/milestone/5

If you are still having trouble with this just let me know.
